unique_ids:
  assets:
    standard-page.html: JADKSVS74BHE5O3KJL4NCWZF4JRTYSR2
    theme.css: 4LQHWJICEOVMRZ5DWMW34TQRJKB3NXLK
  forms:
    Form1: IXLNCA7LCT7VLWEOM32U6H2RGPSNXLCY
    Form1.ItemTemplate1: '1751441552263637031671771.1324'
    PartDetail: '1751437185060751609738477.6289'
  modules: {}
  scripts: {}
  server_modules: {}
